version: '3.9'

services:
  product-service:
    build: 
      context: ./msv-product
      dockerfile: Dockerfile
    container_name: product-service
    image: product
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
      - mysql
    networks:
      - app-network
  
  order-service:
    build: 
      context: ./msv-order
      dockerfile: Dockerfile
    container_name: order-service
    image: order
    ports:
      - "3001:3001"
    depends_on:
      - rabbitmq
      - mysql1
    networks:
      - app-network
  
  rabbitmq:
      image: "rabbitmq:3-management"
      container_name: rabbitmq
      ports:
        - "5672:5672"
        - "15672:15672"
      networks:
        - app-network
  
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3006"
    environment:
      MYSQL_ROOT_PASSWORD: mysql2024
      MYSQL_DATABASE: product 
    networks:
      - app-network

  mysql1:
    image: mysql:latest
    container_name: mysql1
    ports:
      - "3307:3006"
    environment:
      MYSQL_ROOT_PASSWORD: mysql2024
      MYSQL_DATABASE: order 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
