version: '3.9'

services:
  product-service:
    build: 
      context: ./msv-product
      dockerfile: Dockerfile
    container_name: product
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
      - mysql
    networks:
      - app-network
  
  order-service:
    build: 
      context: ./msv-order
      dockerfile: Dockerfile
    container_name: order
    ports:
      - "3001:3001"
    depends_on:
      - rabbitmq
      - mysql
    networks:
      - app-network
  
  rabbitmq:
      image: "rabbitmq:3-management"
      container_name: rabbitmq
      ports:
        - "5672:5672"
        - "15672:15672"
      networks:
        - app-network
  
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysql2024
      - MYSQL_DATABASE=product
      - MYSQL_DATABASE=order
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
